### ISSUE TITLE
Importing devices in V3 with JSON generated by V2 ttn-lw-migrate tool fails

### ISSUE THREAD

**Issue by ThomasBaumgartner** [TheThingsNetwork/lorawan-stack-migrate#23]
#### Summary
The Import of devices with JSON file generated by the lorawan-migration tool fails. I'm using v0.3.0-rc1. If I modifiy the JSON file by deleting the session part the import is successfull.

...

#### Steps to Reproduce

1. Generate a JSON file of a device or entire application with tt_lw_migrate tool
2. Import the generated JSON file using the User Interface on the new ThingNetwork Console (Button import end devices)

#### What do you see now?
The Issue is described here: https://www.thethingsnetwork.org/forum/t/importing-devices-in-v3-with-json-generated-by-v2-ttn-lw-migrate-tool-fails/45169

The error generated by the import tool is: Invaild field mask
![grafik](https://user-images.githubusercontent.com/45274753/112283478-79182b00-8c88-11eb-8226-f2ba2c9b4b85.png)

**Comment by neoaggelos** [comment]
Hi @ThomasBaumgartner, thanks for reporting the issue.

Devices exported with an active session cannot be imported to The Things Stack versions prior to 3.12.0. This is due to a breaking API change with The Things Stack 3.12.0 (unreleased as of yet).

If using earlier versions of The Things Stack, please export devices without their session (add the `--ttnv2.with-session=false` flag in the export command), or (temporarily) use an earlier version [v0.2.0-rc2](https://github.com/TheThingsNetwork/lorawan-stack-migrate/releases/tag/v0.2.0-rc2).

There is also a [PR to add a note for this in the README](#20).

Sorry for the trouble caused, I hope this helps.

**Comment by ThomasBaumgartner** [comment]
Hi @neoaggelos thank you very much for your help. It works perfectly with `--ttnv2.with-session=false`
