### ISSUE TITLE
ttnv3 not in sources list

### ISSUE THREAD

**Issue by fossejc** [TheThingsNetwork/lorawan-stack-migrate#67]
#### Summary

ttnv3 not in sources list when running the command `ttn-lw-migrate sources`
When trying to migrate: source `ttnv3` is not registered
...

#### Steps to Reproduce

1. brew install ttn-lw-migrate 
2. ttn-lw-migrate sources

#### What do you see now?

chirpstack           Migrate from ChirpStack LoRaWAN Network Server
ttnv2                Migrate from The Things Network Stack V2

#### What do you want to see instead?

chirpstack           Migrate from ChirpStack LoRaWAN Network Server
ttnv2                Migrate from The Things Network Stack V2
ttnv3  Migrate from The Things Network Stack

#### Environment

Macos 13.1 (22C65)
Homebrew 4.0.1
Homebrew/homebrew-core (git revision ab00bd21e98; last commit 2023-02-17)

**Comment by happyRip** [comment]
The `ttnv3` source is available in yet unreleased `v9.0.0` version of the migration tool. Due to this it is unavailable in `brew`, but you can try out the release candidate that can be found in [github releases](https://github.com/TheThingsNetwork/lorawan-stack-migrate/releases).  If you intend to go this way, please download the executable suitable for your operating system/device and use it. Otherwise it will be available in `brew` after it's final release. 
Please be vary that when this version of the migration tool is released it may contain differences to the latest release candidate version.
